apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eden-ai-metrics
  namespace: default
  labels:
    app: eden-ai
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: eden-ai
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - default
