from __future__ import annotations

from enum import Enum


class FailureType(str, Enum):
    NONE = "NONE"
    TIMEOUT = "TIMEOUT"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    SCHEMA_REPAIR_FAILED = "SCHEMA_REPAIR_FAILED"
    API_ERROR = "API_ERROR"
    EMPTY_RESPONSE = "EMPTY_RESPONSE"
    SAFETY_REFUSAL = "SAFETY_REFUSAL"


class AuthorityLevel(str, Enum):
    DRAFT = "DRAFT"
    PLAUSIBLE = "PLAUSIBLE"
    EVIDENCE_SUPPORTED = "EVIDENCE_SUPPORTED"
    REPLAY_VERIFIED = "REPLAY_VERIFIED"


class VerificationResult(str, Enum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    INCONCLUSIVE = "INCONCLUSIVE"


class KernelPanicCode(str, Enum):
    ROOT_KEY_UNRESOLVED = "ROOT_KEY_UNRESOLVED"
    REGISTRY_SCHEMA_INVALID = "REGISTRY_SCHEMA_INVALID"
    REGISTRY_SIGNATURE_MISMATCH = "REGISTRY_SIGNATURE_MISMATCH"
    REGISTRY_STALE_VERSION = "REGISTRY_STALE_VERSION"
    REGISTRY_ROOT_KEY_INACTIVE = "REGISTRY_ROOT_KEY_INACTIVE"
    LEDGER_LOCK_TIMEOUT = "LEDGER_LOCK_TIMEOUT"
    LEDGER_CHAIN_BREAK = "LEDGER_CHAIN_BREAK"
    LEDGER_PARSE_FAILURE = "LEDGER_PARSE_FAILURE"
    STATE_FILE_CORRUPT = "STATE_FILE_CORRUPT"
    STATE_VERSION_WRITE_FAILED = "STATE_VERSION_WRITE_FAILED"
    UNPINNED_ROOT_IN_PRODUCTION = "UNPINNED_ROOT_IN_PRODUCTION"
    UNKNOWN_BOOT_FAILURE = "UNKNOWN_BOOT_FAILURE"
