#!/usr/bin/env bash
set -euo pipefail

UPSTREAM_COMMIT="88a8ce0b3346b7422ef417f024db5f45ccae9f5c"
PORT="${PORT:-8000}"
FILES=(
  "index.html"
  "cards.json"
  "policy.json"
  "examples/policy-strict.json"
  "examples/medguide-triage-deck.json"
  "examples/devops-incident-deck.json"
)

echo "SYMCRUCIBLE_TRANSITION_CONSOLE_v0.2 replication runner"
echo "Status: DEMO_INSTRUMENT · TIER_UI / AUTHORITY_WEIGHT_0"
echo "Upstream anchor: ${UPSTREAM_COMMIT}"
echo

if ! command -v git >/dev/null 2>&1; then
  echo "ERROR: git is required for upstream blob-anchor verification." >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 is required to serve the console." >&2
  exit 1
fi

if command -v sha256sum >/dev/null 2>&1; then
  SHA="sha256sum"
elif command -v shasum >/dev/null 2>&1; then
  SHA="shasum -a 256"
else
  echo "ERROR: sha256sum or shasum is required for local observed hashes." >&2
  exit 1
fi

echo "[1/4] Verifying required files exist"
for f in "${FILES[@]}"; do
  test -f "$f" || { echo "ERROR: missing $f" >&2; exit 1; }
done

echo "[2/4] Verifying upstream Git blob anchors from MANIFEST.sha256"
while read -r kind expected path; do
  [[ -z "${kind:-}" || "${kind:0:1}" == "#" ]] && continue
  [[ "$kind" == "UPSTREAM_COMMIT" ]] && continue
  [[ "$kind" == "GIT_BLOB" ]] || continue
  observed="$(git rev-parse "${UPSTREAM_COMMIT}:${path}" 2>/dev/null || true)"
  if [[ -z "$observed" ]]; then
    echo "ERROR: cannot resolve ${UPSTREAM_COMMIT}:${path}" >&2
    exit 1
  fi
  if [[ "$observed" != "$expected" ]]; then
    echo "ERROR: blob anchor mismatch for $path" >&2
    echo "  expected: $expected" >&2
    echo "  observed: $observed" >&2
    exit 1
  fi
  echo "  OK $path"
done < MANIFEST.sha256

echo "[3/4] Writing local observed SHA-256 manifest"
{
  echo "# Observed SHA-256 manifest generated by run.sh"
  echo "# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Upstream commit: ${UPSTREAM_COMMIT}"
  for f in "${FILES[@]}"; do
    $SHA "$f"
  done
} > REPLICATION_OBSERVED.sha256
cat REPLICATION_OBSERVED.sha256

echo
echo "[4/4] Starting local server"
echo "Open: http://localhost:${PORT}/"
echo "Press Ctrl+C to stop."
python3 -m http.server "$PORT"
