; The Garden  |  Config/DefaultInput.ini

[/Script/Engine.InputSettings]
+ActionMappings=(ActionName="SpawnEntity",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=E)
+ActionMappings=(ActionName="SpawnEntity",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=Gamepad_FaceButton_Bottom)
+ActionMappings=(ActionName="OpenLeaderboard",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=Tab)
+ActionMappings=(ActionName="OpenLeaderboard",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=Gamepad_Special_Left)
+ActionMappings=(ActionName="Pause",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=Escape)
+ActionMappings=(ActionName="Pause",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=Gamepad_Special_Right)
+ActionMappings=(ActionName="Interact",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=F)
+ActionMappings=(ActionName="Interact",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=Gamepad_FaceButton_Left)
+AxisMappings=(AxisName="MoveForward",Scale=1.0,Key=W)
+AxisMappings=(AxisName="MoveForward",Scale=-1.0,Key=S)
+AxisMappings=(AxisName="MoveRight",Scale=1.0,Key=D)
+AxisMappings=(AxisName="MoveRight",Scale=-1.0,Key=A)
+AxisMappings=(AxisName="MoveForward",Scale=1.0,Key=Gamepad_LeftY)
+AxisMappings=(AxisName="MoveRight",Scale=1.0,Key=Gamepad_LeftX)
+AxisMappings=(AxisName="LookUp",Scale=-1.0,Key=MouseY)
+AxisMappings=(AxisName="LookRight",Scale=1.0,Key=MouseX)
+AxisMappings=(AxisName="LookUp",Scale=1.0,Key=Gamepad_RightY)
+AxisMappings=(AxisName="LookRight",Scale=1.0,Key=Gamepad_RightX)
